apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: prod
nameSuffix: -prod

labels:
  - pairs:
      environment: prod


patches:
  - path: prod-patch.yaml 
