# overlays/prod/prod-patch.yaml
apiVersion: apps/v1
kind: Deployment
metadata:

  name: my-app

spec:
  replicas: 10

  template:
    metadata:
      labels:
        environment: prod

    spec:

      containers:
        - name: my-app
          image: nginx:latest
